version: '3.8'

networks:
  ecommerce-network:
    name: ecommerce-network
    external: true

services:
  # Frontend de la Tienda
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - API_URL=http://ecommerce-admin:3000/api
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - PORT=4000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ecommerce-network
    restart: unless-stopped

# NOTA: Este frontend se conecta al admin a través de la red externa 'ecommerce-network'
#
# Para usar este frontend:
#
# 1. MODO INDEPENDIENTE (solo frontend con datos mock):
#    docker-compose up --build
#
# 2. MODO CONECTADO (con admin ejecutándose):
#    Primero ejecutar el admin:
#    cd ../next-ecommerce-admin && docker-compose up -d
#
#    Luego ejecutar este frontend:
#    docker-compose up --build
#
# El frontend estará disponible en: http://localhost:4000
# Si el admin está ejecutándose, estará en: http://localhost:3000
